apiVersion: v1
kind: Secret
metadata:
  name: {{ template "generatedata.fullname" . }}
type: Opaque
data:
  GD_DB_PASSWORD: {{ .Values.mysql.mysqlPassword | b64enc | quote }}
  GD_ENCRYPTION_SALT: {{ .Values.salt | b64enc | quote }}